import{initializeApp}from"https://www.gstatic.com/firebasejs/9.22.1/firebase-app.js";import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/9.22.1/firebase-auth.js";import{getDatabase,ref,onValue,push,set,serverTimestamp,get,remove,query,orderByChild,equalTo,update,onDisconnect}from"https://www.gstatic.com/firebasejs/9.22.1/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyBKp-HUZXSGSfBfEhl-HIjaC3Yflpqxg7s",authDomain:"kotogram-9b0b9.firebaseapp.com",databaseURL:"https://kotogram-9b0b9-default-rtdb.firebaseio.com",projectId:"kotogram-9b0b9",storageBucket:"kotogram-9b0b9.firebasestorage.app",messagingSenderId:"755607509917",appId:"1:755607509917:web:29b1b85eea516bde702d74"};
const IMGBB_API_KEY="706ffb03d5653cdf91990abac2ce7a29",app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),$=id=>document.getElementById(id);
let cUser=null,activeCallId=null;

onAuthStateChanged(auth,async u=>{if(u){const sP=await get(ref(db,'users/'+u.uid)),ud=sP.exists()?sP.val():{};if(ud.banned===!0){alert("🚫 Аккаунт заблокирован.");await signOut(auth);window.location.href="../login/login.html";return;}cUser=u;
$('drawer-display-name').textContent=ud.displayName||"Мой профиль";$('drawer-phone-number').textContent=ud.phoneNumber||"";$('drawer-username').textContent=ud.username||"";$('drawer-avatar').src=ud.photoURL||"https://via.placeholder.com/150/cccccc/ffffff?text=?";
const mSR=ref(db,`status/${u.uid}`),cR=ref(db,'.info/connected');onValue(cR,s=>{if(s.val()===!0)onDisconnect(mSR).set({state:'offline',last_seen:serverTimestamp()}).then(()=>set(mSR,{state:'online',last_seen:serverTimestamp()}));});loadChats();listenCalls();}else window.location.href="../login/login.html";});

$('burger-menu-btn').onclick=()=>{$('drawer').classList.add('open');$('drawer-overlay').classList.add('open');};
$('drawer-overlay').onclick=()=>{$('drawer').classList.remove('open');$('drawer-overlay').classList.remove('open');};
$('drawer-logout-btn').onclick=()=>signOut(auth);
$('btn-settings').onclick=()=>window.location.href="../settings/settings.html";

// СОЗДАНИЕ ГРУППЫ
$('btn-open-create-group').onclick=()=>{$('drawer').classList.remove('open');$('drawer-overlay').classList.remove('open');$('create-group-modal').style.display='flex';$('new-group-name').value='';};
$('close-create-group-btn').onclick=()=>$('create-group-modal').style.display='none';
$('confirm-create-group-btn').onclick=async()=>{const gn=$('new-group-name').value.trim();if(!gn)return;$('confirm-create-group-btn').disabled=!0;const gId='g_'+push(ref(db,'groups')).key;await set(ref(db,`groups/${gId}/info`),{name:gn,creator:cUser.uid,timestamp:serverTimestamp(),photoURL:'https://via.placeholder.com/150/3390ec/ffffff?text=G'});await set(ref(db,`groups/${gId}/members/${cUser.uid}`),'creator');await update(ref(db,`userChats/${cUser.uid}/${gId}`),{isGroup:!0,timestamp:serverTimestamp(),lastMessage:'Группа создана'});$('create-group-modal').style.display='none';$('confirm-create-group-btn').disabled=!1; window.location.href=`../pages/chat/chat.html?type=group&id=${gId}`;};

// ГЛОБАЛЬНЫЙ ПОИСК
let searchT=null;
$('search-input').oninput=e=>{clearTimeout(searchT);const q=e.target.value.trim().toLowerCase(),sc=$('search-results-container'),cl=$('chat-list');if(!q){sc.style.display='none';cl.style.display='block';return;}sc.style.display='block';cl.style.display='none';sc.innerHTML='<div style="padding:15px;text-align:center;color:#888;">Поиск...</div>';searchT=setTimeout(async()=>{const s=await get(ref(db,'users'));if(!s.exists()){sc.innerHTML='<div style="padding:15px;text-align:center;color:#888;">Ничего не найдено</div>';return;}sc.innerHTML='';let f=!1;s.forEach(c=>{const u=c.val();if(u.uid===cUser.uid)return;let m=!1;if(q.startsWith('@')){if(u.username&&u.username.toLowerCase().includes(q))m=!0;}else{const p=(u.phoneNumber||'').replace(/\D/g,''),qc=q.replace(/\D/g,'');if((qc&&p.includes(qc))||(u.displayName&&u.displayName.toLowerCase().includes(q))||(u.username&&u.username.toLowerCase().includes(q)))m=!0;}if(m){f=!0;const d=document.createElement('div');d.className='chat-item';d.innerHTML=`<img src="${u.photoURL||'https://via.placeholder.com/150/cccccc/ffffff?text=?'}" class="chat-item-avatar"><div class="chat-item-info"><strong style="display:block;color:#000;">${u.displayName||u.phoneNumber}</strong><span style="font-size:13px;color:#888;">${u.username||''}</span></div>`;d.onclick=()=>{window.location.href=`../pages/chat/chat.html?type=private&id=${u.uid}`;};sc.appendChild(d);}});if(!f)sc.innerHTML='<div style="padding:15px;text-align:center;color:#888;">Ничего не найдено</div>';},500);};

// ЗАГРУЗКА ЛЕНТЫ ЧАТОВ
function loadChats(){onValue(ref(db,'userChats/'+cUser.uid),async s=>{const l=$('chat-list');if(!s.exists()){l.innerHTML='<div style="padding:20px;text-align:center;color:#888;">Нет чатов.<br>Используйте поиск или создайте группу</div>';return;}const cs=[];s.forEach(c=>{const v=c.val(),io=typeof v==='object'&&v!==null;cs.push({id:c.key,isGrp:v.isGroup||!1,timestamp:io?(v.timestamp||0):0,lastMessage:io?(v.lastMessage||'Сообщение'):'Создано'});});cs.sort((a,b)=>b.timestamp-a.timestamp);const cps=cs.map(c=>c.isGrp?get(ref(db,`groups/${c.id}/info`)):get(ref(db,'users/'+c.id))),uss=await Promise.all(cps);l.innerHTML='';cs.forEach((cm,i)=>{const us=uss[i];if(us.exists()){const u=us.val(),itm=document.createElement('div');itm.className='chat-item';let tS='';if(cm.timestamp){const d=new Date(cm.timestamp);tS=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}itm.innerHTML=`<img src="${u.photoURL||(cm.isGrp?'https://via.placeholder.com/150/3390ec/ffffff?text=G':'https://via.placeholder.com/150/cccccc/ffffff?text=?')}" class="chat-item-avatar"><div class="chat-item-info"><div style="display:flex;justify-content:space-between;align-items:baseline;margin-bottom:4px;"><strong style="font-size:16px;color:#000;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:70%;">${u.name||u.displayName||u.phoneNumber}</strong><span style="font-size:12px;color:#888;">${tS}</span></div><div style="font-size:14px;color:#888;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">${cm.lastMessage}</div></div>`;
itm.onclick=()=>window.location.href=`../pages/chat/chat.html?type=${cm.isGrp?'group':'private'}&id=${cm.id}`;l.appendChild(itm);}});});}

// ЗВОНКИ
function listenCalls(){onValue(query(ref(db,'calls'),orderByChild('receiver'),equalTo(cUser.uid)),async s=>{let iCD=null,aRI=null;s.forEach(c=>{const d=c.val();if(d.status==='calling'){iCD=d;aRI=c.key;}});const m=$('incoming-call-modal');if(iCD&&aRI){if(activeCallId===aRI)return;activeCallId=aRI;const cS=await get(ref(db,'users/'+iCD.caller)),u=cS.exists()?cS.val():{};$('caller-avatar').src=u.photoURL||"https://via.placeholder.com/150/cccccc/ffffff?text=?";$('caller-name').textContent=u.displayName||u.phoneNumber||"Неизвестный";m.style.display='flex';$('accept-call-btn').onclick=()=>{activeCallId=null;window.location.href=`../call/call.html?room=${aRI}&mode=receiver`;};$('decline-call-btn').onclick=async()=>{await remove(ref(db,`calls/${aRI}`));m.style.display='none';activeCallId=null;};}else{m.style.display='none';activeCallId=null;}});}
